### ISSUE TITLE
Webpack 4 Issue when running storybook

### ISSUE THREAD

**Issue by ctassparker** [uptick/react-object-list#15]
On `yarn && yarn storybook` i get `TypeError: Cannot read property 'compilation' of undefined`. 

It appears Webpack 4 isn't fully supported by storybook yet, depending on this PR 
https://github.com/storybooks/storybook/pull/3148

Current fix was to drop dependencies in `package.json` to 
```    
"webpack": "3.x.x",
"webpack-cli": "1.x.x"```
```
stack trace: 
```
/home/ctp/Projects/react-object-list/node_modules/@storybook/react/node_modules/dotenv-webpack/node_modules/webpack/lib/DefinePlugin.js:42
		compiler.hooks.compilation.tap(
		              ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/home/ctp/Projects/react-object-list/node_modules/@storybook/react/node_modules/dotenv-webpack/node_modules/webpack/lib/DefinePlugin.js:42:17)
    at Compiler.apply (/home/ctp/Projects/react-object-list/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/ctp/Projects/react-object-list/node_modules/@storybook/react/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/home/ctp/Projects/react-object-list/node_modules/@storybook/react/dist/server/middleware.js:29:40)
    at Object.<anonymous> (/home/ctp/Projects/react-object-list/node_modules/@storybook/react/dist/server/index.js:153:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ctp/Projects/react-object-list/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by ctassparker** [comment]
Storybook merged the PR a day ago, so we can either bump to the latest version or go with this.
